# Generated by Django 5.0.3 on 2026-03-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Alex Rivera', max_length=100)),
                ('email', models.EmailField(default='alex.rivera@ledger.org', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 042-1988', max_length=20)),
                ('role', models.CharField(default='Canteen Manager', max_length=50)),
                ('surplus_threshold', models.CharField(default='25kg (Standard)', max_length=50)),
                ('prediction_model', models.CharField(default='Neural V4.2 (Recommended)', max_length=50)),
                ('auto_redistribution', models.BooleanField(default=True)),
                ('real_time_sensor_sync', models.BooleanField(default=True)),
                ('predictive_route_optimization', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('ngo_broadcasts', models.BooleanField(default=True)),
            ],
        ),
    ]
