# Generated by Django 5.0.3 on 2026-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systempreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('rain_probability', models.FloatField()),
                ('campus_event', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('predicted_footfall', models.IntegerField()),
                ('predicted_surplus_kg', models.FloatField()),
                ('actual_footfall', models.IntegerField(blank=True, null=True)),
                ('actual_surplus_kg', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('sensitivity', models.IntegerField(default=72)),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
    ]
