# Generated by Django 5.0.3 on 2026-03-30 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_predictionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('breakfast', 'Breakfast (7:00–9:00)'), ('lunch', 'Lunch (12:00–14:00)'), ('snacks', 'Snacks (16:00–17:30)'), ('dinner', 'Dinner (19:00–21:00)')], max_length=20)),
                ('student_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('quantity_kg', models.FloatField()),
                ('is_distributed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved for NGO'), ('distributed', 'Distributed'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_to', models.ForeignKey(blank=True, help_text='The NGO this food was sent to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_surplus', to='api.ngo')),
                ('footfall', models.ForeignKey(blank=True, help_text='Links surplus to the footfall record that generated it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_items', to='api.footfall')),
            ],
            options={
                'verbose_name_plural': 'Surplus food',
                'ordering': ['-created_at'],
            },
        ),
    ]
